version: '3.7'
services:
  hls:
    container_name: proxy
    build: ./
    ports:
      - '8080:8085'
    volumes:
#      - ./data:/opt/hlsp/
      - /data/:/opt/hls-proxy
    restart:
        always
        
